# Generated by Django 5.1.3 on 2024-12-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='umbral_stock_invierno',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='umbral_stock_verano',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
