# Generated by Django 5.1.3 on 2024-12-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_umbral_stock_invierno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='umbral_stock_invierno',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='umbral_stock_verano',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
